#ifndef _C_IIC_MASTER_MULTI_H_
#define _C_IIC_MASTER_MULTI_H_

	typedef enum _IIC_MASTER_MULTI_HANDLES {
		IIC_MASTER_MULTI_HANDLE_USER0 = 0,
		IIC_MASTER_MULTI_HANDLE_USER1,
		IIC_MASTER_MULTI_HANDLE_USER2,
		IIC_MASTER_MULTI_HANDLE_MAX,
	} IIC_MASTER_MULTI_HANDLES;

#endif
