/***************************************************************
 * File Name:   mpfs_img2.c
 * Description: Defines an MPFS2 image to be stored in program memory.
 * Processor:   PIC32
 * Compiler:    Microchip C32,XC32
 *
 * NOT FOR HAND MODIFICATION
 * This file is automatically generated by the MPFS2 Utility
 * ALL MODIFICATIONS WILL BE OVERWRITTEN BY THE MPFS2 GENERATOR
 * Generated Fr Apr 23 2021 08:22:51 
 *
 * Software License Agreement
 *
 * Copyright (C) 2012 Microchip Technology Inc.  All rights
 * reserved.
 *
 * Microchip licenses to you the right to use, modify, copy, and distribute
 * software only embedded on a Microchip microcontroller or digital signal 
 * controller that is integrated into your product or third party product
 * (pursuant to the sublicense terms in the accompanying license agreement)

 * You should refer to the license agreement accompanying this 
 * Software for additional information regarding your rights and 
 * obligations.
 *
 * THE SOFTWARE AND DOCUMENTATION ARE PROVIDED "AS IS" WITHOUT
 * WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT
 * LIMITATION, ANY WARRANTY OF MERCHANTABILITY, FITNESS FOR A 
 * PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
 * MICROCHIP BE LIABLE FOR ANY INCIDENTAL, SPECIAL, INDIRECT OR
 * CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA, COST OF
 * PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY OR SERVICES, ANY CLAIMS
 * BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE 
 * THEREOF), ANY CLAIMS FOR INDEMNITY OR CONTRIBUTION, OR OTHER 
 * SIMILAR COSTS, WHETHER ASSERTED ON THE BASIS OF CONTRACT, TORT
 * (INCLUDING NEGLIGENCE), BREACH OF WARRANTY, OR OTHERWISE.
 *
 ***************************************************************/
#include <stdint.h>
#include "system_config.h"

/**************************************
 * MPFS2 Image Data
 **************************************/ 

const uint8_t __attribute__((space(prog),address(DRV_NVM_MEDIA_START_ADDRESS))) __attribute__((keep)) NVM_MEDIA_DATA[DRV_NVM_MEDIA_SIZE*1024] = { \
	0x4d,0x50,0x46,0x53,0x02,0x01,0x03,0x00,0xf0,0x74,0xf0,0x76,0xec,0xa2,0x50,0x00, /* MPFS.....t.v..P. */ \
	0x00,0x00,0x71,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x7b,0x10,0x83,0x60,0x00,0x00, /* ..q.......{..`.. */ \
	0x00,0x00,0x00,0x00,0x5b,0x00,0x00,0x00,0x71,0x00,0x00,0x00,0x04,0x00,0x00,0x00, /* ....[...q....... */ \
	0x7b,0x10,0x83,0x60,0x00,0x00,0x00,0x00,0x00,0x00,0x67,0x00,0x00,0x00,0x75,0x00, /* {..`......g...u. */ \
	0x00,0x00,0x59,0x00,0x00,0x00,0x38,0x0e,0x83,0x60,0x00,0x00,0x00,0x00,0x01,0x00, /* ..Y...8..`...... */ \
	0x79,0x6e,0x52,0x63,0x72,0x64,0x2e,0x62,0x69,0x6e,0x00,0x69,0x6c,0x65,0x52,0x63, /* ynRcrd.bin.ileRc */ \
	0x72,0x64,0x2e,0x62,0x69,0x6e,0x00,0x6e,0x64,0x65,0x78,0x2e,0x68,0x74,0x6d,0x6c, /* rd.bin.ndex.html */ \
	0x00,0x00,0x00,0x00,0x00,0x1f,0x8b,0x08,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xb3, /* ................ */ \
	0xc9,0x28,0xc9,0xcd,0xb1,0xe3,0xe5,0xb2,0x49,0xca,0x4f,0xa9,0x04,0xd2,0x40,0x56, /* .(......I.O...@V */ \
	0x86,0xa1,0x9d,0x6f,0xa5,0x82,0x5b,0x66,0x51,0x71,0x89,0x82,0x47,0x6a,0x62,0x4a, /* ...o..[fQq..GjbJ */ \
	0x66,0x5e,0xba,0x8d,0x3e,0x50,0x10,0x28,0x55,0x00,0x92,0x49,0x03,0xcb,0x14,0x24, /* f^..>P.(U..I...$ */ \
	0x16,0x25,0xa6,0x17,0x25,0x16,0x64,0xe8,0xd9,0xe8,0x17,0x40,0x34,0xea,0x43,0xcd, /* .%..%.d....@4.C. */ \
	0x00,0xaa,0x86,0x18,0x0a,0x00,0xf7,0x4e,0xd3,0x9d,0x5d,0x00,0x00,0x00            /* .......N..]...   */


};

/**************************************
 * MPFS2 C linkable symbols
 **************************************/
// The entire data array is defined as a single variable to 
// ensure that the linker does not reorder the data chunks in Flash when compiler 
// optimizations are turned on.
struct MEDIA_STORAGE_PARTITION_INFO
{
	const char*     partName;           // name that identifies the partition
										// valid names: "mpfs2", "tcpip_storage";
	unsigned long   partStartOffset;    // the absolute starting offset on that media 
	unsigned long   partSize;           // size of the partition, in bytes
} MPFS_IMAGE_PARTITION_INFO = 
{
	"mpfs2",
	(unsigned long)NVM_MEDIA_DATA,
	sizeof(NVM_MEDIA_DATA),
};

/**************************************************************
 * End of MPFS
 **************************************************************/
